/**
 * ISO 3166-1 numeric -> [alpha-2, alpha-3, name].
 *
 * Natural Earth keys countries by numeric id; everything in this product keys
 * them by alpha-2, so something has to bridge the two. Matching on
 * `properties.name` does not work — the data ships "Dem. Rep. Congo",
 * "Bosnia and Herz." and "W. Sahara".
 *
 * The 238 ids here are a superset of those present in world-atlas
 * countries-110m (174), -50m (235) and -10m (238), so the same table is
 * correct at every resolution.
 *
 * Lives in its own module with NO imports on purpose. `db/resolve.ts` needs it
 * on the server and `components/globe/CountryBorders.tsx` needs it in the
 * browser; putting it anywhere that touches Drizzle would drag the Postgres
 * driver into the client bundle. Duplicating it instead was the other option,
 * and two copies of a 238-row lookup drift.
 */

export const COUNTRY_BY_NUMERIC: Readonly<
  Record<string, readonly [iso2: string, iso3: string, name: string]>
> = {
  '004': ['AF', 'AFG', 'Afghanistan'],
  '008': ['AL', 'ALB', 'Albania'],
  '010': ['AQ', 'ATA', 'Antarctica'],
  '012': ['DZ', 'DZA', 'Algeria'],
  '016': ['AS', 'ASM', 'American Samoa'],
  '020': ['AD', 'AND', 'Andorra'],
  '024': ['AO', 'AGO', 'Angola'],
  '028': ['AG', 'ATG', 'Antigua and Barb.'],
  '031': ['AZ', 'AZE', 'Azerbaijan'],
  '032': ['AR', 'ARG', 'Argentina'],
  '036': ['AU', 'AUS', 'Australia'],
  '040': ['AT', 'AUT', 'Austria'],
  '044': ['BS', 'BHS', 'Bahamas'],
  '048': ['BH', 'BHR', 'Bahrain'],
  '050': ['BD', 'BGD', 'Bangladesh'],
  '051': ['AM', 'ARM', 'Armenia'],
  '052': ['BB', 'BRB', 'Barbados'],
  '056': ['BE', 'BEL', 'Belgium'],
  '060': ['BM', 'BMU', 'Bermuda'],
  '064': ['BT', 'BTN', 'Bhutan'],
  '068': ['BO', 'BOL', 'Bolivia'],
  '070': ['BA', 'BIH', 'Bosnia and Herz.'],
  '072': ['BW', 'BWA', 'Botswana'],
  '076': ['BR', 'BRA', 'Brazil'],
  '084': ['BZ', 'BLZ', 'Belize'],
  '086': ['IO', 'IOT', 'Br. Indian Ocean Ter.'],
  '090': ['SB', 'SLB', 'Solomon Is.'],
  '092': ['VG', 'VGB', 'British Virgin Is.'],
  '096': ['BN', 'BRN', 'Brunei'],
  '100': ['BG', 'BGR', 'Bulgaria'],
  '104': ['MM', 'MMR', 'Myanmar'],
  '108': ['BI', 'BDI', 'Burundi'],
  '112': ['BY', 'BLR', 'Belarus'],
  '116': ['KH', 'KHM', 'Cambodia'],
  '120': ['CM', 'CMR', 'Cameroon'],
  '124': ['CA', 'CAN', 'Canada'],
  '132': ['CV', 'CPV', 'Cabo Verde'],
  '136': ['KY', 'CYM', 'Cayman Is.'],
  '140': ['CF', 'CAF', 'Central African Rep.'],
  '144': ['LK', 'LKA', 'Sri Lanka'],
  '148': ['TD', 'TCD', 'Chad'],
  '152': ['CL', 'CHL', 'Chile'],
  '156': ['CN', 'CHN', 'China'],
  '158': ['TW', 'TWN', 'Taiwan'],
  '170': ['CO', 'COL', 'Colombia'],
  '174': ['KM', 'COM', 'Comoros'],
  '178': ['CG', 'COG', 'Congo'],
  '180': ['CD', 'COD', 'Dem. Rep. Congo'],
  '184': ['CK', 'COK', 'Cook Is.'],
  '188': ['CR', 'CRI', 'Costa Rica'],
  '191': ['HR', 'HRV', 'Croatia'],
  '192': ['CU', 'CUB', 'Cuba'],
  '196': ['CY', 'CYP', 'Cyprus'],
  '203': ['CZ', 'CZE', 'Czechia'],
  '204': ['BJ', 'BEN', 'Benin'],
  '208': ['DK', 'DNK', 'Denmark'],
  '212': ['DM', 'DMA', 'Dominica'],
  '214': ['DO', 'DOM', 'Dominican Rep.'],
  '218': ['EC', 'ECU', 'Ecuador'],
  '222': ['SV', 'SLV', 'El Salvador'],
  '226': ['GQ', 'GNQ', 'Eq. Guinea'],
  '231': ['ET', 'ETH', 'Ethiopia'],
  '232': ['ER', 'ERI', 'Eritrea'],
  '233': ['EE', 'EST', 'Estonia'],
  '234': ['FO', 'FRO', 'Faeroe Is.'],
  '238': ['FK', 'FLK', 'Falkland Is.'],
  '239': ['GS', 'SGS', 'S. Geo. and the Is.'],
  '242': ['FJ', 'FJI', 'Fiji'],
  '246': ['FI', 'FIN', 'Finland'],
  '248': ['AX', 'ALA', 'Åland'],
  '250': ['FR', 'FRA', 'France'],
  '258': ['PF', 'PYF', 'Fr. Polynesia'],
  '260': ['TF', 'ATF', 'Fr. S. Antarctic Lands'],
  '262': ['DJ', 'DJI', 'Djibouti'],
  '266': ['GA', 'GAB', 'Gabon'],
  '268': ['GE', 'GEO', 'Georgia'],
  '270': ['GM', 'GMB', 'Gambia'],
  '275': ['PS', 'PSE', 'Palestine'],
  '276': ['DE', 'DEU', 'Germany'],
  '288': ['GH', 'GHA', 'Ghana'],
  '292': ['GI', 'GIB', 'Gibraltar'],
  '296': ['KI', 'KIR', 'Kiribati'],
  '300': ['GR', 'GRC', 'Greece'],
  '304': ['GL', 'GRL', 'Greenland'],
  '308': ['GD', 'GRD', 'Grenada'],
  '316': ['GU', 'GUM', 'Guam'],
  '320': ['GT', 'GTM', 'Guatemala'],
  '324': ['GN', 'GIN', 'Guinea'],
  '328': ['GY', 'GUY', 'Guyana'],
  '332': ['HT', 'HTI', 'Haiti'],
  '334': ['HM', 'HMD', 'Heard I. and McDonald Is.'],
  '336': ['VA', 'VAT', 'Vatican'],
  '340': ['HN', 'HND', 'Honduras'],
  '344': ['HK', 'HKG', 'Hong Kong'],
  '348': ['HU', 'HUN', 'Hungary'],
  '352': ['IS', 'ISL', 'Iceland'],
  '356': ['IN', 'IND', 'India'],
  '360': ['ID', 'IDN', 'Indonesia'],
  '364': ['IR', 'IRN', 'Iran'],
  '368': ['IQ', 'IRQ', 'Iraq'],
  '372': ['IE', 'IRL', 'Ireland'],
  '376': ['IL', 'ISR', 'Israel'],
  '380': ['IT', 'ITA', 'Italy'],
  '384': ['CI', 'CIV', 'Côte d\'Ivoire'],
  '388': ['JM', 'JAM', 'Jamaica'],
  '392': ['JP', 'JPN', 'Japan'],
  '398': ['KZ', 'KAZ', 'Kazakhstan'],
  '400': ['JO', 'JOR', 'Jordan'],
  '404': ['KE', 'KEN', 'Kenya'],
  '408': ['KP', 'PRK', 'North Korea'],
  '410': ['KR', 'KOR', 'South Korea'],
  '414': ['KW', 'KWT', 'Kuwait'],
  '417': ['KG', 'KGZ', 'Kyrgyzstan'],
  '418': ['LA', 'LAO', 'Laos'],
  '422': ['LB', 'LBN', 'Lebanon'],
  '426': ['LS', 'LSO', 'Lesotho'],
  '428': ['LV', 'LVA', 'Latvia'],
  '430': ['LR', 'LBR', 'Liberia'],
  '434': ['LY', 'LBY', 'Libya'],
  '438': ['LI', 'LIE', 'Liechtenstein'],
  '440': ['LT', 'LTU', 'Lithuania'],
  '442': ['LU', 'LUX', 'Luxembourg'],
  '446': ['MO', 'MAC', 'Macao'],
  '450': ['MG', 'MDG', 'Madagascar'],
  '454': ['MW', 'MWI', 'Malawi'],
  '458': ['MY', 'MYS', 'Malaysia'],
  '462': ['MV', 'MDV', 'Maldives'],
  '466': ['ML', 'MLI', 'Mali'],
  '470': ['MT', 'MLT', 'Malta'],
  '478': ['MR', 'MRT', 'Mauritania'],
  '480': ['MU', 'MUS', 'Mauritius'],
  '484': ['MX', 'MEX', 'Mexico'],
  '492': ['MC', 'MCO', 'Monaco'],
  '496': ['MN', 'MNG', 'Mongolia'],
  '498': ['MD', 'MDA', 'Moldova'],
  '499': ['ME', 'MNE', 'Montenegro'],
  '500': ['MS', 'MSR', 'Montserrat'],
  '504': ['MA', 'MAR', 'Morocco'],
  '508': ['MZ', 'MOZ', 'Mozambique'],
  '512': ['OM', 'OMN', 'Oman'],
  '516': ['NA', 'NAM', 'Namibia'],
  '520': ['NR', 'NRU', 'Nauru'],
  '524': ['NP', 'NPL', 'Nepal'],
  '528': ['NL', 'NLD', 'Netherlands'],
  '531': ['CW', 'CUW', 'Curaçao'],
  '533': ['AW', 'ABW', 'Aruba'],
  '534': ['SX', 'SXM', 'Sint Maarten'],
  '540': ['NC', 'NCL', 'New Caledonia'],
  '548': ['VU', 'VUT', 'Vanuatu'],
  '554': ['NZ', 'NZL', 'New Zealand'],
  '558': ['NI', 'NIC', 'Nicaragua'],
  '562': ['NE', 'NER', 'Niger'],
  '566': ['NG', 'NGA', 'Nigeria'],
  '570': ['NU', 'NIU', 'Niue'],
  '574': ['NF', 'NFK', 'Norfolk Island'],
  '578': ['NO', 'NOR', 'Norway'],
  '580': ['MP', 'MNP', 'N. Mariana Is.'],
  '581': ['UM', 'UMI', 'U.S. Minor Outlying Is.'],
  '583': ['FM', 'FSM', 'Micronesia'],
  '584': ['MH', 'MHL', 'Marshall Is.'],
  '585': ['PW', 'PLW', 'Palau'],
  '586': ['PK', 'PAK', 'Pakistan'],
  '591': ['PA', 'PAN', 'Panama'],
  '598': ['PG', 'PNG', 'Papua New Guinea'],
  '600': ['PY', 'PRY', 'Paraguay'],
  '604': ['PE', 'PER', 'Peru'],
  '608': ['PH', 'PHL', 'Philippines'],
  '612': ['PN', 'PCN', 'Pitcairn Is.'],
  '616': ['PL', 'POL', 'Poland'],
  '620': ['PT', 'PRT', 'Portugal'],
  '624': ['GW', 'GNB', 'Guinea-Bissau'],
  '626': ['TL', 'TLS', 'Timor-Leste'],
  '630': ['PR', 'PRI', 'Puerto Rico'],
  '634': ['QA', 'QAT', 'Qatar'],
  '642': ['RO', 'ROU', 'Romania'],
  '643': ['RU', 'RUS', 'Russia'],
  '646': ['RW', 'RWA', 'Rwanda'],
  '652': ['BL', 'BLM', 'St-Barthélemy'],
  '654': ['SH', 'SHN', 'Saint Helena'],
  '659': ['KN', 'KNA', 'St. Kitts and Nevis'],
  '660': ['AI', 'AIA', 'Anguilla'],
  '662': ['LC', 'LCA', 'Saint Lucia'],
  '663': ['MF', 'MAF', 'St-Martin'],
  '666': ['PM', 'SPM', 'St. Pierre and Miquelon'],
  '670': ['VC', 'VCT', 'St. Vin. and Gren.'],
  '674': ['SM', 'SMR', 'San Marino'],
  '678': ['ST', 'STP', 'São Tomé and Principe'],
  '682': ['SA', 'SAU', 'Saudi Arabia'],
  '686': ['SN', 'SEN', 'Senegal'],
  '688': ['RS', 'SRB', 'Serbia'],
  '690': ['SC', 'SYC', 'Seychelles'],
  '694': ['SL', 'SLE', 'Sierra Leone'],
  '702': ['SG', 'SGP', 'Singapore'],
  '703': ['SK', 'SVK', 'Slovakia'],
  '704': ['VN', 'VNM', 'Vietnam'],
  '705': ['SI', 'SVN', 'Slovenia'],
  '706': ['SO', 'SOM', 'Somalia'],
  '710': ['ZA', 'ZAF', 'South Africa'],
  '716': ['ZW', 'ZWE', 'Zimbabwe'],
  '724': ['ES', 'ESP', 'Spain'],
  '728': ['SS', 'SSD', 'S. Sudan'],
  '729': ['SD', 'SDN', 'Sudan'],
  '732': ['EH', 'ESH', 'W. Sahara'],
  '740': ['SR', 'SUR', 'Suriname'],
  '748': ['SZ', 'SWZ', 'eSwatini'],
  '752': ['SE', 'SWE', 'Sweden'],
  '756': ['CH', 'CHE', 'Switzerland'],
  '760': ['SY', 'SYR', 'Syria'],
  '762': ['TJ', 'TJK', 'Tajikistan'],
  '764': ['TH', 'THA', 'Thailand'],
  '768': ['TG', 'TGO', 'Togo'],
  '776': ['TO', 'TON', 'Tonga'],
  '780': ['TT', 'TTO', 'Trinidad and Tobago'],
  '784': ['AE', 'ARE', 'United Arab Emirates'],
  '788': ['TN', 'TUN', 'Tunisia'],
  '792': ['TR', 'TUR', 'Turkey'],
  '795': ['TM', 'TKM', 'Turkmenistan'],
  '796': ['TC', 'TCA', 'Turks and Caicos Is.'],
  '798': ['TV', 'TUV', 'Tuvalu'],
  '800': ['UG', 'UGA', 'Uganda'],
  '804': ['UA', 'UKR', 'Ukraine'],
  '807': ['MK', 'MKD', 'North Macedonia'],
  '818': ['EG', 'EGY', 'Egypt'],
  '826': ['GB', 'GBR', 'United Kingdom'],
  '831': ['GG', 'GGY', 'Guernsey'],
  '832': ['JE', 'JEY', 'Jersey'],
  '833': ['IM', 'IMN', 'Isle of Man'],
  '834': ['TZ', 'TZA', 'Tanzania'],
  '840': ['US', 'USA', 'United States of America'],
  '850': ['VI', 'VIR', 'U.S. Virgin Is.'],
  '854': ['BF', 'BFA', 'Burkina Faso'],
  '858': ['UY', 'URY', 'Uruguay'],
  '860': ['UZ', 'UZB', 'Uzbekistan'],
  '862': ['VE', 'VEN', 'Venezuela'],
  '876': ['WF', 'WLF', 'Wallis and Futuna Is.'],
  '882': ['WS', 'WSM', 'Samoa'],
  '887': ['YE', 'YEM', 'Yemen'],
  '894': ['ZM', 'ZMB', 'Zambia'],
}

/** Alpha-2 for a Natural Earth numeric id, or null when it carries none. */
export function iso2FromNumeric(id: string | number | undefined): string | null {
  if (id === undefined || id === null) return null
  const row = COUNTRY_BY_NUMERIC[String(id).padStart(3, '0')]
  return row ? row[0] : null
}

/** iso2 -> display name, derived once from the numeric table above. */
const NAME_BY_ISO2: Record<string, string> = {}
for (const row of Object.values(COUNTRY_BY_NUMERIC)) {
  NAME_BY_ISO2[row[0]] = row[2]
}
// Kosovo carries no ISO numeric id in Natural Earth but the map draws it.
NAME_BY_ISO2['XK'] = 'Kosovo'

/** Display name for an alpha-2 code, falling back to the code itself. */
export function nameFromIso2(iso2: string): string {
  return NAME_BY_ISO2[iso2.toUpperCase()] ?? iso2.toUpperCase()
}

/** 🇧🇬 from "BG" — regional-indicator pair; empty string for junk input. */
export function flagEmoji(iso2: string): string {
  const code = iso2.toUpperCase()
  if (!/^[A-Z]{2}$/.test(code)) return ''
  const A = 0x1f1e6
  return String.fromCodePoint(
    A + code.charCodeAt(0) - 65,
    A + code.charCodeAt(1) - 65,
  )
}
