-- ExploreYC World — real audience numbers: cached platform reach + live presence.
--
-- Mirrors the two tables database.py creates for SQLite. Additive and
-- idempotent; nothing here touches plots, payments or promotions.
--
-- The rule these tables serve lives in backend/world_audience.py: every figure
-- the product prints about its own audience must be a measurement. NULL here
-- means "never measured", and the API turns it into null, which the UI omits.
-- There is no default, no seed row and no placeholder number anywhere below.

-- The last SUCCESSFUL read of the Vercel Web Analytics API, cached so the
-- public endpoint never makes an outbound request. One row, enforced.
CREATE TABLE IF NOT EXISTS world_audience_cache (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    -- All nullable on purpose: a row only exists after a real read, and a
    -- future field we cannot measure must be able to stay empty.
    visitors_30d INTEGER,
    pageviews_30d INTEGER,
    -- Distinct countries with at least one visitor in the window. A FLOOR
    -- rather than a total when countries_capped is true (the breakdown filled
    -- its 100-row page and Vercel bucketed the tail into "Others").
    countries_count INTEGER,
    countries_capped BOOLEAN NOT NULL DEFAULT FALSE,
    -- [{"iso": "US", "visitors": 643}, ...], biggest first.
    top_countries JSONB NOT NULL DEFAULT '[]'::jsonb,
    window_days INTEGER,
    -- Provenance, printed in the UI's InfoTip. 'vercel_web_analytics'.
    source TEXT,
    -- End of the measured window, ISO-8601 UTC with a literal Z. This is what
    -- the UI means by "measured at"; updated_at is when the row was written.
    measured_at TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Live presence: "N watching now".
--
-- Two columns, and the omissions are the design. No IP, no user id, no cookie,
-- no user agent — the session id is generated by the client, kept in
-- sessionStorage, and dies with the tab. Rows older than a few minutes are
-- garbage and are deleted on the next heartbeat.
CREATE TABLE IF NOT EXISTS world_presence (
    session_id TEXT PRIMARY KEY,
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Both reads on this table are "inside the last N seconds".
CREATE INDEX IF NOT EXISTS idx_world_presence_last_seen ON world_presence (last_seen);
